# Site
repository: heksaani/CV
#favicon: images/
# Content configuration version
version: 2

# Personal info
name: Heidi Putkuri
title: Research Assistant at Folkh채lsan Research Center
email: heidi.putkuri@helsinki.fi
website: www.github.com/heksaani

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: heksaani
instagram_username: heksaani
linkedin_username: heidi-putkuri

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: "Hi, my name's Heidi currently pursuing a Master's in Life Science Informatics at the University of Helsinki. To enhance my skills I am also working part time as a research assistant at Folkh채lsan Research Center.\nWhile I am very much interested in biological data my current interet are leaning more towards software development.\nI am also starting to work on my Master's thesis this coming Spring. It will focus on the pipelines used in analysing \nLong Read Sequencing data. \n "
content:
- title: Projects # Title for the section
  layout: list
  content:
  - layout: top-middle
    border: weak
    title: Citation management application
    link: https://github.com/Jouchef/ohtu_kandi_viitteet
    additional_links:
    - title: Github page for project
      icon: fab fa-github
      url: github.com/Jouchef/ohtu_kandi_viitteet
    #quote: >
    #  A modern simple static resume template and theme. Powered by Jekyll and GitHub pages.
    description: "It was a great learning experience and I learned a lot about working in a team and using version control. We used <mark>Python</mark> and <mark>Flask</mark> to create a web application \nthat allows users to upload citations and then download them in a bibtext format. We did all of this while using Scrum as our project management method\n"
  - layout: top-middle
    border: weak
    title: Database application
    link: https://github.com/heksaani/database-application
    description: "We used <mark>Python</mark> and <mark>Flask</mark> to create a web application \nthat allows users to upload citations and then download them in a bibtext format. We did all of this while using Scrum as our project management method\n"
- title: Experience # Title for the section
  layout: list # Type of content section (list/text)
  content:
  - layout: top-middle
    title: Folkh채lsan Research Center
    link: https://www.folkhalsan.fi/en/knowledge/research/genetics/group-turunen/
    # link_text: boringcompany.com
    sub_title: Research Assistant
    caption: January 2023 - Present
    quote: >
      Using different bioinformatic tools to analyse primarily sequencing data. 
    description: | # this will include new lines to allow paragraphs
    title: Folkh채lsan Research Center
    link: https://www.folkhalsan.fi/en/knowledge/research/genetics/group-turunen/
    # link_text: boringcompany.com
    sub_title: Research Assistant
    caption: January 2023 - Present
    quote: >
      Using different bioinformatic tools to analyse primarily sequencing data. 
    description: | # this will include new lines to allow paragraphs

- title: Education # Title for the section
  layout: list # Type of content section (list/text)
  content:
  - layout: top-middle
    title: University of Helsinki
    caption: 2019 - Present
    sub_title: BSc of Science (2019-2022) &  MSc of Science (2022-present)
    quote: >
      Pursuing a Master's in Life Science Informatics with study track Bioinformatics and Systems Medicine.
    description: "I am currently pursuing a Master's in Life Science Informatics at the University of Helsinki. While I am very much interested in biological data \nmy current interest in software development and machine learning is taking me futher away from the academic side.\n\n"
- title: A Little More About Me
  layout: text
  content: | # this will include new lines to allow paragraphs
    Alongside my interests in computers and data some of my other interests and hobbies are:
    - Poetry
    - Art
    - Music
    - Photography
    - Knitting


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-seo-tag
